services:
  - type: web
    name: bulk-sms-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: TZ
        value: Asia/Kolkata
